# Terragrount has a problem with "terragrunt-plan" with data_source form dependency

**debek** commented *Aug 6, 2020*

Hi!

terragrunt apply-all and terragrunt validate-all works well.

This is my configuration:

```
include {
  path = find_in_parent_folders()
}

dependency "common_infra" {
  config_path = "../test-test-gcp-infra"
  skip_outputs = false
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
  mock_outputs = {
    project_name = "test-test"
    cluster_name = "test-cluster"
    gke_region = "us-central1"
  }
}

inputs = {
  namespace = "test"
  project           = dependency.common_infra.outputs.project_name
  cluster_name      = dependency.common_infra.outputs.cluster_name
  region            = dependency.common_infra.outputs.gke_region
}
```

After plan-all i get error:


```
Error: Invalid template interpolation value

  on ../modules/test_tenant/main.tf line 28, in provider "helm":
  28:     host = "https://${data.google_container_cluster.gke_cluster.endpoint}"
    |----------------
    | data.google_container_cluster.gke_cluster.endpoint is null

The expression result is null. Cannot include a null value in a string
template.
```

My peace of code from this place is:


```
provider "helm" {
  kubernetes {
    host = "https://${data.google_container_cluster.gke_cluster.endpoint}"
    client_certificate = base64decode(
      data.google_container_cluster.gke_cluster.master_auth.0.client_certificate,
    )
    client_key = base64decode(
      data.google_container_cluster.gke_cluster.master_auth.0.client_key,
    )
    cluster_ca_certificate = base64decode(
      data.google_container_cluster.gke_cluster.master_auth.0.cluster_ca_certificate,
    )

  }
}
```


I suppose that data cannot be retrieved because don't exist yet. After apply-all everything is well. Using terraform plan it works well so I suppose that something wrong is with terragrunt.


<br />
***


**yorinasub17** commented *Aug 6, 2020*

Is the `plan-all` run after or before the `apply-all` when it errors?

If before, then the issue is that your mocks are pointing to a cluster that doesn't exist, and hence the data source fails. I would be surprised if `terraform plan` works in the same situation (you haven't applied anything), but if you are getting it to work, then you need to make sure the inputs you used for the dependency vars are the same as that provided in the mocks.

If after, then this is a bug and will take a look.
***

