# Terragrunt Custom retryable_errors Not Matching

**AaronKalair** commented *Mar 30, 2021*

Hey,

I've defined a custom `retryable_errors` block like so

```
retryable_errors = [
  "(?s).*Error: error listing tags for resource.*"
]
```

Inside of my `terragrunt.hcl` file.

Because I occasionally see this error:

```
Error: error listing tags for resource (<AWS ARN>): CacheClusterNotFound: <CLUSTER NAME> is either not present or not available.
	status code: 404, request id: <REQUEST ID>
```

When creating Elasticache Clusters (it appears to be some sort of eventual consistency error, because the resource does exist)

However `terragrunt run-all apply` never retries on that error.

Have I misunderstood how the Regex should be written, or am I doing something else wrong?
<br />
***


**brikis98** commented *Apr 7, 2021*

Hm, your regex seems fine... Could you share the full log output where you get that error and Terragrunt's logging around it? And perhaps turn up the [log level](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-level)?

Also, what version of Terragrunt are you on?
***

**AaronKalair** commented *Apr 7, 2021*

Hey,

Thanks for the reply,

* We're using terragrunt 0.28.2
* We have debug logging turned on already, this is the logging around the error: 


```
aws_elasticache_replication_group.redis: Still creating... [5m30s elapsed]
aws_elasticache_replication_group.redis: Still creating... [5m30s elapsed]
aws_elasticache_replication_group.redis: Still creating... [5m30s elapsed]
aws_elasticache_replication_group.redis: Still creating... [5m30s elapsed]

Error: error listing tags for resource (arn:aws:elasticache:us-east-1:<AWS ACCOUNT ID>:cluster:<CLUSTER_NAME>): CacheClusterNotFound: <CLUSTER_NAME> is either not present or not available.
	status code: 404, request id: <REQUEST ID>


time=2021-03-31T07:22:59Z level=info msg=Module /srv/actions-runner/_work/terragrunt/terragrunt/dev/us-east-1/reference/<PRODUCT NAME>/redislock/02 has finished with an error: Hit multiple errors:
Hit multiple errors:
exit status 1 prefix=[/srv/actions-runner/_work/terragrunt/terragrunt/dev/us-east-1/reference/<PRODUCT NAME>/redislock/02] 
```
***

**brikis98** commented *Apr 8, 2021*

Strange. It does seem like a bug. Have you tried simplifying the regex to see if that would help? 

We're a bit buried right now, so we might not be able to dig in for a bit. If anyone has some time available, a PR is very welcome.
***

**infraredgirl** commented *Apr 8, 2021*

I could not repro this with terragrunt 0.28.2.

Since it's hard to induce the exact failures described in the ticket, I used this simple example:

```
$ cat main.tf
resource "null_resource" "example" {
  triggers = {
    always_recreate = timestamp()
  }

provisioner "local-exec" {
    command = "echo 'aws_elasticache_replication_group.redis: Still creating...\n\nError: error listing tags for resource (arn:aws:elasticache:us-east-1:<AWS ACCOUNT ID>:cluster:<CLUSTER_NAME>): CacheClusterNotFound: <CLUSTER_NAME> is either not present or not available. \n	status code: 404, request id: <REQUEST ID> \n' && exit 1"
  }
}
```
```
$ cat terragrunt.hcl
retryable_errors = [
  "(?s).*Error: error listing tags for resource.*"
]
```

Running `terragrunt run-all apply` results in three retries before it finally gives up, which is the expected behavior.

Regex matching also works as expected, in the example above the regex matches against the error string.


***

**AaronKalair** commented *Apr 26, 2021*

Hey,

Thanks for the reply, we couldn't get that Regex to work for us still, however my colleague added these additional Regexes and now one of them does match the error and triggers the retries we needed:

```
  "(?s).*Error: error listing tags for resource.*",
  "(?s).*CacheClusterNotFound.*",
  "(?s).*elasticache.*"
```

Still not sure why the original one doesn't match, but this is a perfectly fine workaround for us, so feel free to close this now :) 

Thanks everyone for the help.
***

**infraredgirl** commented *Apr 27, 2021*

Thanks for closing the loop @AaronKalair! Let us know if you still hit any issues, in the meantime I'll close this bug.
***

