# Dependency mock doesn't work when other outputs exists

**gregorycuellar** commented *Jul 24, 2021*

# Description
When some outputs already exists in the state, terragrunt doesn't mock the non existing ones.

I have created a small project to illustrate the issue, and I link 2 zips files which represents the 2 steps process :
- [first_step.zip](https://github.com/gruntwork-io/terragrunt/files/6872252/first_step.zip) => represent the first apply of the project, everything is ok
- [second_step.zip](https://github.com/gruntwork-io/terragrunt/files/6872253/second_step.zip) => an output is added to the module s1 and used in dependency in s2, the plan of s2 failed if the s1 module is not applied. I would have expected that the mock value will have been used.

# Steps to reproduce

1. Apply both s1 and s2 from zip file first_step

2. Add modifications from the second_step zip file and try to plan s2
An error is thrown because the newly added output does not exits and the mock is not used.

# Screenshots of all steps
The issue is on step 5.

## With first_step.zip
1. If we make a terragrunt plan on s1, it's ok, we can see the output :
![01_first_step_s1_plan](https://user-images.githubusercontent.com/1319575/126864650-c5576181-9302-4322-b1f3-e46d39647f51.png)

2. If we make a terragrunt plan on s2, it's ok, we can see the fake output, so mocks are working :
![02_first_step_s2_plan](https://user-images.githubusercontent.com/1319575/126864707-f99762a6-0314-4667-8dca-2dae126af448.png)

3. We can apply s1 and s2, so the state is modified
![03_first_step_s1_apply](https://user-images.githubusercontent.com/1319575/126864728-3623c56e-b84c-45de-a713-40316f552ebf.png)
![04_first_step_s2_apply](https://user-images.githubusercontent.com/1319575/126864734-f6090efb-359a-4226-8b34-3d0989a84c88.png)

## With second_step.zip, so with a new output in s1

4. If we make a terragrunt plan on s1, it's ok, we can see the new output :
![05_second_step_s1_plan](https://user-images.githubusercontent.com/1319575/126864751-a4f08f3b-9ae9-4639-bd62-c5f6d6b2748a.png)

5. If we make a terragrunt plan on s2, there is an error, the attribute is not found so the mock is not used. I would have expected that the mock is used for newly added output as it's not in the state.
![06_second_step_s2_plan](https://user-images.githubusercontent.com/1319575/126864774-b3ca6a47-b4d3-4c72-82c6-534af47d3516.png)

6. we can apply s1, so the state is modified
![07_second_step_s1_apply](https://user-images.githubusercontent.com/1319575/126864784-674a5ef8-71de-46f4-b861-4434af2552e6.png)

7. The plan on s2, now works
![08_second_step_s2_plan_after_s1_apply](https://user-images.githubusercontent.com/1319575/126864794-3fdb8051-44a2-4d1f-a0cb-a92655f195fe.png)


<br />
***


**yorinasub17** commented *Jul 24, 2021*

This is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/940. Please follow that thread for updates on if and when we implement something to support this use case.
***

