# TestNewSignalsForwarderMultiple is flaky when run from top level

**mrtyler** commented *Apr 26, 2017*

Spinning this off from #194.

I was not able to cause this test to fail by running its module alone: `cd shell ; go test -v -parallel 128`.

However, I still see this test fail about 25% of the time when running as part of the full suite. Here's the setup:
* macos sierra 10.12.3 on a macbook pro. I was doing stuff on the machine during the test run (browser, shell, youtube videos) but no unusual load or anything I would expect to cause a test to fail so often
* terragrunt at aa9ae94a868b53d9e2f381c363313d6114e6f25d
* glide 0.12.3
* terraform 0.9.3
* Run this from top of terragrunt working copy: `for i in $(seq 1 22) ; do rm -f test.out ; go test -v -parallel 128 $(glide novendor) > test.out 2>&1 ; rc=$? ; if grep "FAIL" test.out ; then echo "FAIL with return code $rc" ; else echo "PASS with return code $rc" ; fi ; done`

This resulted in 17 successes and 5 failures. TestNewSignalsForwarderMultiple was the only test that failed during the run.

Flaky tests are difficult to debug, especially when they only flake in complex scenarios like 128 threads of simultaneous test action, so I won't be offended if you choose to close this out without a lot of action. I just wanted y'all to be aware.
<br />
***


**brikis98** commented *Apr 26, 2017*

Thank you for filing! I'm not sure what would cause this. cc @asobrien and @mildred who looked at this code more recently than me.
***

**asobrien** commented *Apr 28, 2017*

I haven't been able to recreate the failures @mrtyler has been seeing, even when putting my system (similar hardware) under `stress`.

The error you're seeing:

```
--- FAIL: TestNewSignalsForwarderMultiple (7.54s)
        assertions.go:226: ^M                          ^M       Error Trace:    run_shell_cmd_test.go:121
                ^M      Error:          Not equal:
                ^M                      expected: 10
                ^M                      received: 12
FAIL
FAIL    github.com/gruntwork-io/terragrunt/shell        7.564s
```

stems from the fact more `SIGINT` signals were emitted from the parent process than were received by the subprocess (`test_sigint_multiple.sh` in this case).

I'm curious, if disabling parallelism from this test would mitigate the issue. The relevant line is [here](https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd_test.go#L83).

If dropped signals continue to be a problem on various platforms, the test could be made less stringent by modifying [this statement](https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd_test.go#L121) to something like:

```
assert.True(t, retCode <= interrupts, "Subprocess exited before receiving all expected signals")
```

***

**mrtyler** commented *Apr 28, 2017*

> I haven't been able to recreate the failures @mrtyler has been seeing

Bummer :(.

A few new things I've tried in an attempt to get you more data (10 runs per scenario):
* Re-update everything: go 1.7.1 -> 1.8.1 (forgot to do this before), terraform 0.9.3 -> 0.9.4, latest terragrunt source (471d1b735301362238ba3e79178f7908faba87cb).
   * 20% failure rate
* Try different values for `-parallel`: 64 and 256.
   * 64 -> 10% failure rate
   * 256 -> 0% failure rate! To me this is... unexpected, so I ran it again and got a 20% failure rate. I suspect this is a result of my poor science in this experiment: no control (the 0% failure run happened while I was away from the computer and therefore not perturbing it) and too-small sample size.
* Disable parallelism for this test, as suggested above. (I didn't collect timing data to determine how this affects overall suite execution time.)
   * 20% failure rate
* Change assertion, as suggested above.
   * 0% failure rate, although another test failed (below). Ran it again and got no failures on any tests.
```
--- FAIL: TestTerragruntStackCommands (115.65s)
FAIL
FAIL    github.com/gruntwork-io/terragrunt/test 116.667s
FAIL with return code 1
```

I don't know if any of this is meaningful :).

Let me know if you'd like me to PR the assertion change.
***

**asobrien** commented *May 4, 2017*

Thanks for running thorough tests and sharing the detailed data! I'm not sure why that final test failed but `TestTerragruntStackCommands` is unrelated to `TestNewSignalsForwarderMultiple`.

I think we can safely relax the requirement on the test by modifying the assert (as above) to check that, indeed, multiple signals were sent to the subprocess before exiting (e.g., `retCode <= interrupts`). I'd also check that multiple signals were received by the subprocess (e.g., `retCode == expectedInterrupts`). With those assertions, we're not really modifying the spirit of the test and we're restricting it to what's happening inside of userland. @mrtyler, I'd think a PR that encapsulated those changes would close this issue. Does that sound reasonable @brikis98? Nonetheless, I'm not sure why you're seeing signals being collapsed so frequently by the kernel.

A word on what this test is designed to do: this test is designed to ensure that `NewSignalsForwarder` waits for the subprocess to finish even when multiple signals are required to exit. A scenario where this is relevant with `terraform` is when sending a SIGINT (`ctrl-c`) when running a `terraform plan`. The first SIGINT enables a trace logging, a subsequent SIGINT will cause terraform to stop execution and exit.


***

**brikis98** commented *May 4, 2017*

@asobrien Seems reasonable to me!
***

**mrtyler** commented *May 5, 2017*

I guess this can be closed now?
***

**brikis98** commented *May 5, 2017*

Yup, thanks!
***

