# Add TargetPrefix as config input to access bucket logging

**ina-stoyanova** commented *Jan 22, 2021*

This PR is in response to [this issue. ](https://github.com/gruntwork-io/terragrunt/issues/1437)

Here's the TODOs:
- [x] add new variable for the `TFStateLogs`
- [x] update code when creating a new logs bucket for the TF state bucket logs
- [x] update tests
- [x] test
- [x] update official/any docs 
<br />
***


**ina-stoyanova** commented *Feb 16, 2021*

I've tested this today - but came across this error. I can't quite figure out what I need to do to overcome it, but am sure I've seen it before. Any help would be appreciated!

<img width="593" alt="Screenshot 2021-02-16 at 17 39 21" src="https://user-images.githubusercontent.com/32835571/108100671-242c3800-707e-11eb-83ab-a746a73bcfd9.png">

Otherwise, the tests pass, however, if this manual test doesn't - I'm even more confused where's the issue. 
***

**ina-stoyanova** commented *Feb 17, 2021*

> Implementation LGTM. For the test failure, my guess is that you ran it once before you updated terragruntOnlyConfigs. In that case, terragrunt will generate the backend.tf file with the new setting included, and then won't regenerate because it exists. Does it work if you remove that file to force regeneration?

Unfortunately, still no luck. So what I've done exactly is: Update the `terragrunt.hcl` that I'm testing with to look like:
```
# Configure Terragrunt to automatically store tfstate files in an S3 bucket
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    encrypt = true
    bucket = "test-ina-4-1"
    key = "terraform.tfstate"
    region = "us-west-2"
    dynamodb_table = "test-ina-4-1"
    enable_lock_table_ssencryption = true
    accesslogging_bucket_name = "test-ina-access-logs-4-1"
    accesslogging_target_prefix = "TFStateLogs/"
  }
}
```
I then deleted the generated `backend.tf`that gets generated. Ran apply again on the `terragrunt.hcl` and still get the same error. Not sure if I need to be doing anything else?
***

**ina-stoyanova** commented *Mar 5, 2021*

This unfortunately has slipped my radar the last few weeks! I am looking into closing it now.
***

**ina-stoyanova** commented *Mar 5, 2021*

I've tested this and I believe it's ready to go! 
***

**ina-stoyanova** commented *Mar 9, 2021*

Good for another review! 
***

**ina-stoyanova** commented *Mar 10, 2021*

Cool @brikis98 @robmorgan I've now followed your guidance on how to check if it has been provided. In reality, checking for `xxx == ""` was also behaving the same at the parsing level, as it would render the map element as null instead of empty string, but from a reader's point - how it is now, seems to be better! (Let me know if you do think otherwise).

Also, I've added an extra test to check specifically the case with using the default `TargetPrefix` value. The test cases covered now are:
 - when a value is provided (the test expects a value of `logs/`, but it is the same scenario if it was an empty string)
 - when the attribute is not provided at all, that it sets TargetPrefix to the default value
 
 I've also updated the docs to reflect this. 
 
 More feedback welcome! ðŸ™‚ 

***

**ina-stoyanova** commented *Mar 11, 2021*

Thanks for the reviews, merging now! :) 
***

