# Implement Error Hooks

**smitthakkar96** commented *Jan 5, 2022*

Fixes #1522 
<br />
***


**smitthakkar96** commented *Jan 5, 2022*

@yorinasub17 @Ben10k @brikis98 can you please review? 
***

**smitthakkar96** commented *Jan 7, 2022*

@denis256 addressed your comments 
***

**smitthakkar96** commented *Jan 11, 2022*

@denis256 thanks for the approval, I see you are also the codeowner for this repo. Could please help merging this? 
***

**denis256** commented *Jan 11, 2022*

Hi, will be good to have additional review/approval from other people before merge
***

**smitthakkar96** commented *Jan 12, 2022*

@yorinasub17 @rhoboat @zackproser @brikis98 can we have one more reviewon this as suggested by @denis256 ? 
***

**rhoboat** commented *Jan 12, 2022*

Reviewing!
***

**smitthakkar96** commented *Jan 12, 2022*

Thanks @rhoboat for your suggestions. Just merged them :)
***

**smitthakkar96** commented *Jan 12, 2022*

> I have some questions.
> 
> Does it make sense to always process the error hooks after the other hooks? If you have an after hook that is specified to run on error, what happens? This hook will run first, then the error hook. Is that always the right sequencing? How do we know?



@rhoboat good question! Initially I was confused about the execution order. I wasn't sure where should I start this discussion but I think we can deprecate `run_on_error` from before/after hooks in favour of error hooks in future. Why? 
- Because it's very confusing (which one to use)
- Currently if there is no way for the downstream command/script that will be executed by the before/after hooks to know whether it is being executed because of an error or success. If others agree maybe we should add deprecation warning for `run_on_error`. WDYT? 

Edit: Thinking out loud maybe we don't need to deprecate but maybe we can make sure people don't use both `run_on_error` flag together with error hooks. Maybe add some sort of validation. Basically making them mutually exclusive
***

**rhoboat** commented *Jan 12, 2022*

@smitthakkar96 This turned out to be a long response, so I've made sections. Bear with me! 🐻 

## Deprecating the `run_on_error`
For argument's sake: let's see what's the difference between an after_hook with run_on_error and an error_hook:

```
  after_hook "after_hook_1" {
    commands = ["apply", "plan"]
    execute = ["touch","after.out"]
    run_on_error = true
  }
```

The closest we can get to that with error_hook is

```
  error_hook "error_hook_1" {
    commands  = ["apply", "plan"]
    execute   = ["touch", "after.out"]
    on_errors = [".*"]
  }
```

Are these identical? No, because the after_hook will run regardless of whether there are errors, but the error_hook will only run if there are errors. Taken together, the error_hook is redundant. So I see the error_hook as a more specific way to handle the error-only case.

If you get rid of `run_on_error`, you will have to do:

```
  after_hook "after_hook_1" {
    commands = ["apply", "plan"]
    execute = ["touch","after.out"]
  }
```

plus

```
  error_hook "error_hook_1" {
    commands  = ["apply", "plan"]
    execute   = ["touch", "after.out"]
    on_errors = [".*"]
  }
```
Now, the after_hook makes sure it touches after.out only if there are no errors, and the error_hook makes sure it touches after.out if there are errors.

So I think we can't deprecate the `run_on_error` feature without making it harder to do the same thing. 

## Error/success
> Currently if there is no way for the downstream command/script that will be executed by the before/after hooks to know whether it is being executed because of an error or success.

That is true, however, this the main feature for `run_on_error`. It's for the set of cases where you don't want an error to interrupt execution of a particular hook. Is that still useful / needed? (I would also like to hear from people whether it is.) With the addition of `error_hook` we can handle specific error cases, so I do think this is an important feature.

## Execution order

I've been noodling on this a little more, and I think if we're going with error handling as other languages do it, the ordering should be different. I'll start by describing what I think the intent of each of the hooks is:

`after_hook` : run this thing if there's no errors
`after_hook` with `run_on_error` : always run this thing (like `always` and `finally` in typical exception handling parlance)
`error_hook` : run this thing only if there's some specific errors (or all errors with `".*"`) and it's meant to be used specifically to _handle_ the error. In the docs included for this PR, we're advising that you think of this like error handling.. That is, when you catch an error, you execute the catch block _before_ the finally/always blocks. Right?

Given that, I think the ideal execution order should be the following.

1. `before_hooks`
2. `after_hooks` without `run_on_error`
3. `error_hooks`
4. `after_hooks` with `run_on_error`

I also think this is doable from an implementation standpoint, but will not be as clean as you have it in the PR now.

### More intuitive naming?

The above feels intuitive from an execution standpoint, but it's hard to keep this in mind when writing terragrunt. It would be nice if we could do this, but make it easy to understand. Would naming help? Would it be any better if `run_on_error` for the `after_hook` was renamed to `finally` or `always`? I feel like `run_on_error` is clear, but `always = true` also reads better. `run_on_error` could be taken to mean "only run in case of error", which is wrong. `always` doesn't contain the word "error" but it is very clear that it runs "always" (whether or not there's an error).

But there's still the mental overhead of remembering that an `error_hook` which handles the specific error thrown will run before the `after_hook` in cases of error. Is this really as bad as I'm making it sound? WDYT?
***

**smitthakkar96** commented *Jan 12, 2022*

Hey thanks for putting a great deal of thoughts into the execution order 😄. Here is what I think

> That is true, however, this the main feature for `run_on_error`. It's for the set of cases where you don't want an error to interrupt execution of a particular hook. Is that still useful / needed? (I would also like to hear from people whether it is.)

I just realised that I have a such use-case too. During plan regardless of error I want to continue the execution. My use-case is we have a utility that would move state files in S3 incase of renames and path changes (we have folders split per teams `squads/<squad_name>/module`). We rely on `git diff` to detect renames and move operations. When service responsibility changes the modules move from one squad folder to another. What we do with hooks is something like below:

``` hcl
terraform {
  before_hook "before_plan" {
    commands     = ["plan"]
    execute      = [
      local.migrate_states_binary,
      "--yes",
    ]
    working_dir = local.repo_path
  }
  after_hook "after_plan" {
    commands     = ["plan"]
    execute      = [
      local.migrate_states_binary,
      "--rollback",
      "yes",
    ]
    working_dir = local.repo_path
    run_on_error = true
  }
  before_hook "before_apply" {
    commands     = ["apply"]
    execute      = [
      local.migrate_states_binary,
      "--yes",
    ]
    working_dir = local.repo_path
  }
  error_hook "rollback_on_apply_failure" {
    commands     = ["apply"]
    execute      = [
      local.migrate_states_binary,
     "--rollback",
      "--yes",
    ]
    on_errors = [".*"]
  }
}
```
I guess above the example would look ugly without `run_on_error` where after plan we want to rollback the state changes incase developer doesn't decide to apply.


> The above feels intuitive from an execution standpoint, but it's hard to keep this in mind when writing terragrunt. It would be nice if we could do this, but make it easy to understand. Would naming help? Would it be any better if `run_on_error` for the `after_hook` was renamed to `finally` or `always`? I feel like `run_on_error` is clear, but `always = true` also reads better. `run_on_error` could be taken to mean "only run in case of error", which is wrong. `always` doesn't contain the word "error" but it is very clear that it runs "always" (whether or not there's an error).

I like the idea of renaming it to `always` however it will break backwards compatibility, not sure what is the guideline to do that in `gruntworks`, if changing name is hard maybe we can improve the documentation as a part of this PR explaining when to use `run_on_error`, when to use `error_hooks` and also document the order of execution. 

> Given that, I think the ideal execution order should be the following.

I like the execution order and I think if well documented there won't be mental overhead of remembering that an `error_hook` is executed before `after_hooks` with `run_on_error`. 

Should I work on improving docs and changing the execution order and we can open a separate issue (we can get some more feedback from community, maybe gruntworks can reach out to their customers internally too asking for feedback on naming) to rename `run_on_apply` to `always`?
***

**smitthakkar96** commented *Jan 13, 2022*

@yorinasub17 thanks for your review, apart from nits and fixing the bug, should I also change execution order of hooks like @rhoboat suggested? What are your thoughts on execution order? 
***

**yorinasub17** commented *Jan 13, 2022*

RE: execution order

I think ideally and what is most intuitive, is if the hooks are executed in the order that it is defined. That is, if you had the following:

```hcl
terraform {
  after_hook "always" {
    commands = ["plan"]
    execute = ["echo", "always"]
    run_on_error = true
  }
  after_hook "on_success" {
    commands = ["plan"]
    execute = ["echo", "success"]
  }
  error_hook "on_error" {
    commands = ["plan"]
    execute = ["echo", "error"]
    on_errors = [".*"]
  }
  after_hook "last" {
    commands = ["plan"]
    execute = ["echo", "last"]
    run_on_error = true
  }
}
```

On error, the output should be:

```
always
error
last
```

and on success, it should be:

```
always
success
last
```

This mimics how terraform `local-exec` provisioners work, and personally would be much easier to reason about because you don't have to know terragrunt internals of how hooks are processed.

This is the disadvantage of introducing a new block, as it makes it hard to know the order of the blocks when they are interleaved.

The only way I think we can implement this is if we use the approach terraform takes of using labels to identify the hook type - E.g.:

```hcl
terraform {
  hook "after" "always" {
    commands = ["plan"]
    execute = ["echo", "always"]
    run_on_error = true
  }
  hook "after" "on_success" {
    commands = ["plan"]
    execute = ["echo", "success"]
  }
  hook "error" "on_error" {
    commands = ["plan"]
    execute = ["echo", "error"]
    on_errors = [".*"]
  }
  hook "after" "last" {
    commands = ["plan"]
    execute = ["echo", "last"]
    run_on_error = true
  }
}
```

That said, this is a rather drastic backward incompatible change, but FWIW, terragrunt is still a pre-1.0 project and we haven't really identified the stable API yet. I think this is at least worth a consideration in an RFC discussion.

In any case, at this stage, I believe the best course of action is to avoid prescribing and mentioning an execution order and leaving that as undefined. That is, the basic execution order of after and error hooks running after the commands is defined and set, but in what order those individual hooks are run is not specified or guaranteed (similar to the unspecified order of iterating through a map in most languages). NOTE: we should document that it is undefined.

Then separately, we should open an RFC discussing what the actual execution order of hooks we want terragrunt to enforce and implement.

That way, we can consider the ideal UX of hook ordering without being tied to implementation details, and also we can be more systematic about the proposal rather than it being implemented/discussed on the fly in a PR.
***

**rhoboat** commented *Jan 13, 2022*

Thanks @yorinasub17 for further insights into the execution order! It makes sense to respect the lexical ordering (i.e., the order that the hooks appear in the code). I didn't even think of that. 

I agree with execution order being a separate issue we can tackle later. Let's not block this PR on that. I think it makes good enough sense as it is!
***

**smitthakkar96** commented *Jan 14, 2022*

> bug: the new error hook blocks need to be handled in the respective merge functions for `include`.


@yorinasub17 @rhoboat I was about to push a commit to above comment but PR got merged so I created a new PR to handle the merge part https://github.com/gruntwork-io/terragrunt/pull/1982

***

**alikhil** commented *Apr 11, 2023*

Hello!

Is it possible to pass catched error to hook now? I checked the code and it seems like it cannot
***

**zackproser** commented *Apr 11, 2023*

@alikhil could you please open a new issue and include all the relevant details so that we can better assist you? 

* Which version are you running?
* What command are you typing?
* What output are you expecting? 
* What output are you getting? 

Thank you!
***

